Polski = {
    "Str1": "Login",
    "Str2": "Nieprawidłowe hasło",
    "Str3": "Hasło",
    "Str4": "Stwórz hasło",
    "Str5": "Podaj swoje hasło",
    "Str6": "Powtórz swoje hasło",
    "Str7": "Nie stworzyłeś hasła. Po zalogowaniu się wejdż w ustawienia i stwórz hasło aby chronić swoje dane",
    "Str8": "Podane hasła nie są takie same",
    "Str9": "Zaloguj się", 
    "Str10": "Menadżer Haseł",
    "Str11": "Program się zamknie, aby zastosować zmiany",
    "Str12": "Koniec",
    "Str13": "Pole: ",
    "Str14": "Zamknij",
    "Str15": "Chwilowo nie masz żadnych haseł.\nDodaj hasła używając przycisku 'Dodaj' ",
    "Str16": "Dodaj",
    "Str17": "Ustawienia",
    "Str18": "Usuń",
    "Str19": "Anuluj",
    "Str20": "Wybierz pozycję do usunięcia",
    "Str21": "Dodaj nową pozycję",
    "Str22": "Pola nie mogą pozostać puste",
    "Str23": "Nazwa",
    "Str24": "Zapisz",
    "Str25": "Ogólne",
    "Str26": "Wybierz motyw",
    "Str27": "Przyciski",
    "Str28": "Autozmiana: ",
    "Str29": "Wciśnij przycisk (Esc = Anuluj)",
    "Str30": "Zarządzaj",
    "Str31": "Przywróc do ustawień początkowych (razem z hasłami)",
    "Str32": "Stare hasło",
    "Str33": "Nowe hasło",
    "Str34": "Powtórz nowe hasło",
    "Str35": "Zmień hasło",
    "Str36": "UWAGA: Stare hasło nie będzie aktywne. Upewnij się, że zapamiętasz nowe hasło",
    "Str37": "Kontynuować?",
    "Str38": "Kontynuuj",
    "Str39": "Wyeksportuj hasła",
    "Str40": "UWAGA: Hasła zostaną zapisane w pliku tekstowym. Upewnij się, że plik będzie przechowywany w bezpiecznym miejscu",
    "Str41": "Menadżer haseł PyPass napisany w języku Python przy użyciu bibliotek m. in. tkinter ",
    "Str42": "Wersja",
    "Str43": "Wybierz serwis do którego chcesz się zalogować",
    "Str44": "Resetowanie programu",
    "Str45": "UWAGA: Stracisz wszytkie dane zapisane w programie, uwzgledniając hasła. Jeżeli nie znasz haseł zapisanych w programie, zapisz je teraz",
    "Str46": "Zostawić hasło?",
    "Str47": "Czy chcesz zostawić obecne hasło",
    "Str48": "Miejsce pliku z hasłami",
    "Str49": "Przycisk wklejania: ",
    "Str50": "O programie",
    "Str51": "Wybierz język",
    "Str52": "Zresetuj program, aby zastosować wszystkie zmiany",
    "Str53": "Język został zmieniony",
    "Str54": "Zmiana Hasła"
}

English = {
    "Str1": "Login",
    "Str2": "Incorrect password",
    "Str3": "Password",
    "Str4": "Create a password",
    "Str5": "Enter your password",
    "Str6": "Repeat your password",
    "Str7": "You didn't set a password. This is EXTREMELY insecure, please go to settings and set a password to protect your data",
    "Str8": "Passwords don't match",
    "Str9": "Login",
    "Str10": "PyPass Password Manager",
    "Str11": "The program will now close for the changes to take effect",
    "Str12": "Finish",
    "Str13": "Field: ",
    "Str14": "Close",
    "Str15": "You currently have no passwords saved.\nCreate some using the 'Add' button below",
    "Str16": "Add",
    "Str17": "Settings",
    "Str18": "Delete",
    "Str19": "Cancel",
    "Str20": "Select the entry to delete",
    "Str21": "Add a new entry",
    "Str22": "Fields cannot be blank",
    "Str23": "Name",
    "Str24": "Save",
    "Str25": "General",
    "Str26": "Choose the app's theme",
    "Str27": "Bindings",
    "Str28": "Autochange: ",
    "Str29": "Press the key to use, Esc to cancel",
    "Str30": "Manage",
    "Str31": "Reset to vanilla settings (including passwords)",
    "Str32": "Old password",
    "Str33": "New password",
    "Str34": "Repeat new password",
    "Str35": "Change the Password",
    "Str36": "WARNING: The old password will no longer be active. Make sure to remember your new password or save it in a safe place",
    "Str37": "Continue?",
    "Str38": "Continue",
    "Str39": "Export passwords",
    "Str40": "WARNING: All of your passwors will be saved to a plain text file which makes them vurnelable to be stolen. DO NOT share the file with people you do not trust and make sure the file isn't easily accessible",
    "Str41": "PyPass Password Manager written in python using tkinter and other built-in python libraries",
    "Str42": "Version",
    "Str43": "Choose the service to which you want to login",
    "Str44": "Resetting the password manager",
    "Str45": "WARNING: You will lose all passwords currently saved in the program and start over. If you dont know the passwords stored by the program, use the 'Extract all passwords' button first or change passwords to these services",
    "Str46": "Keep the current password?",
    "Str47": "Do you want to keep the current password?",
    "Str48": "Save data location",
    "Str49": "Paste Button: ",
    "Str50": "About PyPass",
    "Str51": "Choose your language",
    "Str52": "Restart the program for all changes to take effect",
    "Str53": "Language has been changed",
    "Str54": "Changing the password"
}
